language: python
install:
  - pip install -r requirements.txt
  - true
# command to run tests
script:
  - python manage.py test

#services:
#  - mysql
#
#before_install:
#- mysql -e 'CREATE DATABASE IF NOT EXISTS test;'