language: python

install:
  - pip install -r requirements.txt
  -
# command to run tests
script:
  - pytest

#services:
#  - mysql
#
#before_install:
#- mysql -e 'CREATE DATABASE IF NOT EXISTS test;'