language: python

install:
  - pip install -r requirements.txt

script:
  - cd library
  - python manage.py migrate
  - python manage.py test

#services:
#  - mysql
#
#before_install:
#- mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
#########